# Generated by Django 6.0.6 on 2026-06-22 22:05

import shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(max_length=13, unique=True, validators=[shared.validators.validate_cedula_ec]),
        ),
    ]
