# Generated by Django 6.0.6 on 2026-06-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_customer_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Brand Image'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='Group Image'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='suppliers/', verbose_name='Supplier Image'),
        ),
    ]
