# Generated by Django 6.0.6 on 2026-07-08 19:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='create_at',
        ),
        migrations.AddField(
            model_name='departamento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
