# Generated by Django 6.0.6 on 2026-07-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_empleado_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='grava_iva',
            field=models.BooleanField(default=True, verbose_name='Graba el iba del 15%?'),
        ),
    ]
